version: 2
registries:
  github:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/maven-release
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 4
      exclude:
        - "no.nav.familie*"
    open-pull-requests-limit: 10
    registries:
      - github
    groups:
      interne-avhengigheter:
        patterns:
          - "no.nav.familie:*"
          - "no.nav.familie.kontrakter:*"
          - "no.nav.familie.felles:*"
          - "no.nav.familie.eksterne.kontrakter:*"
      spring-med-avhengigheter:
        patterns:
          - "org.springframework*"
          - "no.nav.security*"
          - "org.springdoc*"
      utvikler-avhengigheter:
        dependency-type: development
        exclude-patterns:
          - "org.springframework*"
          - "org.springdoc*"
          - "no.nav.security*"
          - "no.nav.familie:*"
          - "no.nav.familie.kontrakter:*"
          - "no.nav.familie.felles:*"
          - "no.nav.familie.eksterne.kontrakter:*"
      prod-avhengigheter:
        dependency-type: production
        exclude-patterns:
          - "org.springframework*"
          - "org.springdoc*"
          - "no.nav.security*"
          - "no.nav.familie:*"
          - "no.nav.familie.kontrakter:*"
          - "no.nav.familie.felles:*"
          - "no.nav.familie.eksterne.kontrakter:*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 4
      exclude:
        - "no.nav.familie*"
    open-pull-requests-limit: 10
    groups:
      workflows:
        patterns:
          - "*"
